# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@1.0
      with:
        username: 'github'
        server: 'davwil00.duckdns.org' 
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY  }}
        local_path: './build/*'
        remote_path: '/gloomhaven-shop/shop'
