# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
      env: 
        REACT_APP_GIST_ID: 465d3de5a1fe3c32fc082d4089b864a4
    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'github'
        server: ${{secrets.SSH_URL}}
        ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
        local_path: './build/*'
        remote_path: '/var/www/gloomhaven-shop/shop'
        port: 18022
